"""Bounded, import-aware static hints; application source is never executed."""

import ast
import os
import re
from pathlib import Path

EXCLUDED_DIRECTORIES = {
    "docs",
    "doc",
    "documentation",
    "examples",
    "example",
    "samples",
    "sample",
    "demos",
    "demo",
    "tests",
    "test",
    "__tests__",
    "fixtures",
    "__fixtures__",
    "mocks",
    "__mocks__",
    "testdata",
    "vendor",
    "vendors",
    "third_party",
    "third-party",
    "external",
    "deps",
    "dependencies",
    "node_modules",
    "site-packages",
    "venv",
    "__pycache__",
    "generated",
    "__generated__",
    "dist",
    "build",
    "target",
    "coverage",
    "htmlcov",
}
NON_APPLICATION_NAMES = {
    "test",
    "tests",
    "spec",
    "specs",
    "example",
    "examples",
    "sample",
    "samples",
    "demo",
    "demos",
    "fixture",
    "fixtures",
    "mock",
    "mocks",
    "conftest",
    "generated",
    "bundle",
    "min",
}
MAX_FILES = 1500
MAX_FILE_BYTES = 500_000
MAX_SCAN_BYTES = 20_000_000
MAX_CANDIDATES = 200
MAX_COVERAGE_DETAILS = 200
REVIEW_CONTEXT_LINES = 50
AGENT_ROLES = {"serving", "background", "evaluation", "development_utility", "unknown"}
PYTHON_ENTRYPOINTS = {
    "agents.Agent",
    "agents.agent.Agent",
    "pydantic_ai.Agent",
    "pydantic_ai.agent.Agent",
    "langchain.agents.create_agent",
    "langchain.agents.AgentExecutor",
    "langgraph.prebuilt.create_react_agent",
    "langgraph.graph.StateGraph",
    "crewai.Agent",
    "agno.agent.Agent",
    "smolagents.CodeAgent",
    "smolagents.ToolCallingAgent",
    "autogen.AssistantAgent",
    "autogen.ConversableAgent",
    "autogen_agentchat.agents.AssistantAgent",
    "google.adk.agents.Agent",
    "google.adk.agents.LlmAgent",
    "google.adk.agents.SequentialAgent",
    "llama_index.core.agent.workflow.FunctionAgent",
    "llama_index.core.agent.workflow.ReActAgent",
    "llama_index.core.agent.workflow.AgentWorkflow",
}
JS_ENTRYPOINTS = {
    ("@openai/agents", "Agent"),
    ("@openai/agents-core", "Agent"),
    ("langchain", "createAgent"),
    ("langchain/agents", "createAgent"),
    ("langchain/agents", "AgentExecutor"),
    ("@langchain/langgraph", "StateGraph"),
    ("@langchain/langgraph/prebuilt", "createReactAgent"),
    ("@mastra/core/agent", "Agent"),
}


def application_path(path):
    parts = Path(path).parts
    if any(part.startswith(".") or part.casefold() in EXCLUDED_DIRECTORIES for part in parts):
        return False
    stem = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", Path(path).stem)
    return not (set(re.split(r"[^a-z0-9]+", stem.casefold())) & NON_APPLICATION_NAMES)


def generated(source):
    return bool(
        re.search(
            r"^\s*(?:#|//|/\*|\*)[^\n]*(?:@generated|auto[- ]?generated|generated by|do not edit)",
            source[:2000],
            re.IGNORECASE | re.MULTILINE,
        )
    )


def eligible_suggestion(root, path):
    if not application_path(path):
        return False
    source = root / path
    try:
        if (
            source.is_symlink()
            or not source.resolve().is_relative_to(root)
            or any(parent.is_symlink() for parent in source.parents if parent.is_relative_to(root))
        ):
            return False
        if not source.is_file():
            return source.is_dir()
        with source.open("rb") as stream:
            return not generated(stream.read(2000).decode(errors="replace"))
    except OSError:
        return False


def source_context(root, path, line, lines=REVIEW_CONTEXT_LINES):
    """Return a bounded source window around a statically detected definition."""

    if type(line) is not int or line < 1 or type(lines) is not int or not 1 <= lines <= 100:
        return None
    relative = Path(path)
    if relative.is_absolute() or not application_path(relative):
        return None
    root = Path(root).resolve()
    source = root / relative
    try:
        resolved = source.resolve()
        if source.is_symlink() or not resolved.is_relative_to(root) or not source.is_file():
            return None
        with source.open("rb") as stream:
            raw = stream.read(MAX_FILE_BYTES + 1)
        if len(raw) > MAX_FILE_BYTES:
            return None
    except OSError:
        return None
    source_lines = raw.decode(errors="replace").splitlines()
    if not source_lines or line > len(source_lines):
        return None
    before = (lines - 1) // 2
    start = max(0, min(line - 1 - before, len(source_lines) - lines))
    end = min(len(source_lines), start + lines)
    return {
        "start_line": start + 1,
        "end_line": end,
        "source": "\n".join(source_lines[start:end]),
    }


def _name(call, fallback):
    for keyword in call.keywords:
        if keyword.arg == "name" and isinstance(keyword.value, ast.Constant):
            if isinstance(keyword.value.value, str) and keyword.value.value.strip():
                return keyword.value.value.strip()[:160]
    return fallback[:160]


class PythonEntries(ast.NodeVisitor):
    def __init__(self):
        self.bindings = {}
        self.scope = []
        self.entries = {}
        self.graphs = {}
        self.recognized_calls = set()
        self.unresolved = []

    def qualified(self, node):
        if isinstance(node, ast.Subscript):
            return self.qualified(node.value)
        if isinstance(node, ast.Name):
            return self.bindings.get(node.id, "")
        if isinstance(node, ast.Attribute):
            parent = self.qualified(node.value)
            return f"{parent}.{node.attr}" if parent else ""
        return ""

    def visit_Import(self, node):
        for alias in node.names:
            self.bindings[alias.asname or alias.name.split(".")[0]] = (
                alias.name if alias.asname else alias.name.split(".")[0]
            )

    def visit_ImportFrom(self, node):
        for alias in node.names:
            if alias.name == "*":
                self.bindings.clear()
            elif node.level or not node.module:
                self.bindings.pop(alias.asname or alias.name, None)
            else:
                self.bindings[alias.asname or alias.name] = f"{node.module}.{alias.name}"

    def visit_FunctionDef(self, node):
        self.bindings.pop(node.name, None)
        previous = self.bindings, self.graphs
        self.bindings, self.graphs = self.bindings.copy(), {}
        for value in ast.walk(node):
            if isinstance(value, ast.Name) and isinstance(value.ctx, ast.Store):
                self.bindings.pop(value.id, None)
            elif isinstance(value, ast.arg):
                self.bindings.pop(value.arg, None)
        self.scope.append(node.name)
        for statement in node.body:
            self.visit(statement)
        self.scope.pop()
        self.bindings, self.graphs = previous

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_ClassDef(self, node):
        self.bindings.pop(node.name, None)
        previous = self.bindings, self.graphs
        self.bindings, self.graphs = self.bindings.copy(), {}
        self.scope.append(node.name)
        for statement in node.body:
            self.visit(statement)
        self.scope.pop()
        self.bindings, self.graphs = previous

    def visit_Assign(self, node):
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        names = [name for target in targets if (name := self.assignment_name(target))]
        if names and isinstance(node.value, ast.Call):
            call = self.qualified(node.value.func)
            symbol = ".".join([*self.scope, names[0]])
            graph = None
            func = node.value.func
            if (
                isinstance(func, ast.Attribute)
                and func.attr == "compile"
                and isinstance(func.value, ast.Name)
            ):
                graph = self.graphs.get(func.value.id)
                if graph:
                    call = graph["call"]
                    self.entries.pop(graph["symbol"], None)
            if call in PYTHON_ENTRYPOINTS:
                self.recognized_calls.add(id(node.value))
                entry = {
                    "name": _name(node.value, names[0]),
                    "symbol": symbol,
                    "line": node.lineno,
                    "call": call,
                }
                self.describe_identity(entry, node.value)
                self.record_entry(entry)
                if call.endswith(".StateGraph") and not graph:
                    self.graphs[names[0]] = entry
        for name in names:
            self.bindings.pop(name, None)
            if not (
                isinstance(node.value, ast.Call)
                and self.entries.get(".".join([*self.scope, name]), {})
                .get("call", "")
                .endswith(".StateGraph")
            ):
                self.graphs.pop(name, None)
        if node.value is not None:
            self.visit(node.value)

    visit_AnnAssign = visit_Assign

    def record_entry(self, entry):
        previous = self.entries.get(entry["symbol"])
        if previous and previous["line"] != entry["line"]:
            # One binding may have several conditional constructors. Keep a single
            # reviewable identity and report alternatives instead of guessing instances.
            lines = sorted(
                set(previous.get("constructor_lines", [previous["line"]]) + [entry["line"]])
            )
            previous["constructor_lines"] = lines
            limits = [
                item
                for item in previous.get("identity_limits", [])
                if item["code"] != "multiple_constructors"
            ]
            limits.append(
                {
                    "code": "multiple_constructors",
                    "reason": "This binding has alternative constructors at lines "
                    + ", ".join(map(str, lines))
                    + ".",
                    "action": "Review the conditional definitions; add explicit instance bindings if they represent different agents.",
                }
            )
            previous["identity_limits"] = limits
            return
        self.entries[entry["symbol"]] = entry

    @staticmethod
    def assignment_name(node):
        """Keep the owning class/method and attribute in the stable source identity."""
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.Attribute):
            owner = PythonEntries.assignment_name(node.value)
            return f"{owner}.{node.attr}" if owner else None
        return None

    def describe_identity(self, entry, call):
        name = next((item.value for item in call.keywords if item.arg == "name"), None)
        dynamic = name is not None and not (
            isinstance(name, ast.Constant) and isinstance(name.value, str)
        )
        entry["identity_kind"] = "factory" if dynamic and self.scope else "declaration"
        if dynamic:
            owner = self.scope[-1] if self.scope else entry["symbol"]
            label = re.sub(r"^(make|create|build|run)_", "", owner).removesuffix("_tool")
            entry["name"] = (label.replace("_", " ").strip().capitalize() + " factory")[:160]
            entry["identity_limits"] = [
                {
                    "code": "dynamic_name",
                    "reason": "Agent names depend on runtime configuration; instances are unresolved.",
                    "action": "Review the factory and add explicit instance bindings if needed.",
                }
            ]

    def visit_Return(self, node):
        if isinstance(node.value, ast.Call):
            call = self.qualified(node.value.func)
            if call in PYTHON_ENTRYPOINTS:
                self.recognized_calls.add(id(node.value))
                symbol = ".".join([*self.scope, "return"])
                entry = {
                    "name": _name(node.value, self.scope[-1] if self.scope else "Agent"),
                    "symbol": symbol,
                    "line": node.lineno,
                    "call": call,
                }
                self.describe_identity(entry, node.value)
                self.record_entry(entry)
        self.generic_visit(node)

    def visit_Call(self, node):
        call = self.qualified(node.func)
        if call in PYTHON_ENTRYPOINTS and id(node) not in self.recognized_calls:
            self.unresolved.append(
                {
                    "line": node.lineno,
                    "constructor": call,
                    "reason": "unsupported_binding",
                    "action": "Review this constructor and add an explicit agent binding.",
                }
            )
        self.generic_visit(node)


def python_entries(source):
    visitor = PythonEntries()
    visitor.visit(ast.parse(source))
    return list(visitor.entries.values())


# Keep offsets/newlines while excluding comments and literals from call matching.
_JS_NONCODE = re.compile(
    r'//[^\n]*|/\*[\s\S]*?\*/|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`(?:\\.|[^`\\])*`'
)
_JS_IMPORT = re.compile(r"\bimport\s+(?!type\b)([^;]*?)\s+from\s*([\'\"])([^\'\"]+)\2")
_JS_ASSIGN = re.compile(
    r"\b(?:const|let|var)\s+([\w$]+)(?:\s*:\s*[\w$.<>\[\] |]+)?\s*=\s*(?:await\s+)?(?:new\s+)?([\w$]+(?:\.[\w$]+)*)(?:\s*<[^;\n()]{1,200}>)?\s*\("
)


def javascript_entries(source):
    masked = _JS_NONCODE.sub(lambda m: re.sub(r"[^\n]", " ", m[0]), source)
    imports = {}
    require_declarations = set()
    for match in _JS_IMPORT.finditer(source):
        if not masked[match.start() :].startswith("import"):
            continue
        clause, package = match[1].strip(), match[3]
        namespace = re.fullmatch(r"\*\s+as\s+([\w$]+)", clause)
        if namespace:
            imports[namespace[1]] = (package, "")
        elif clause.startswith("{") and clause.endswith("}"):
            for item in clause[1:-1].split(","):
                named = re.fullmatch(r"\s*([\w$]+)(?:\s+as\s+([\w$]+))?\s*", item)
                if named:
                    imports[named[2] or named[1]] = (package, named[1])
    for match in re.finditer(
        r"\b(?:const|let|var)\s+([\w$]+|\{[^}]+\})\s*=\s*require\(\s*(['\"])([^'\"]+)\2\s*\)",
        source,
    ):
        if not masked[match.start() :].startswith(("const", "let", "var")):
            continue
        clause, package = match[1], match[3]
        require_declarations.add(match.start())
        if clause.startswith("{"):
            for item in clause[1:-1].split(","):
                named = re.fullmatch(r"\s*([\w$]+)(?:\s*:\s*([\w$]+))?\s*", item)
                if named:
                    imports[named[2] or named[1]] = (package, named[1])
        else:
            imports[clause] = (package, "")
    # A shadowed import is ambiguous to this bounded recognizer; omit it conservatively.
    shadowed = {
        m[1]
        for m in re.finditer(r"\b(?:class|function|const|let|var)\s+([\w$]+)", masked)
        if m.start() not in require_declarations
    }
    for parameters in re.findall(r"\(([^()]*)\)\s*(?:=>|\{)", masked):
        shadowed.update(re.findall(r"\b[\w$]+\b", parameters))
    shadowed.update(re.findall(r"\b([\w$]+)\s*=>", masked))
    entries, graphs = {}, {}
    for match in _JS_ASSIGN.finditer(masked):
        symbol, target = match[1], match[2]
        base, _, member = target.partition(".")
        package, imported = imports.get(base, ("", ""))
        call = (package, member or imported)
        graph = graphs.get(base) if member == "compile" else None
        if graph:
            call = graph["call"]
            entries.pop(base, None)
        if (base in shadowed and not graph) or call not in JS_ENTRYPOINTS:
            continue
        name = re.match(r"\s*\{\s*name\s*:\s*([\'\"])([^\'\"\n]+)\1", source[match.end() :])
        entry = {
            "name": name[2][:160] if name else symbol[:160],
            "symbol": symbol,
            "line": source[: match.start()].count("\n") + 1,
            "call": call,
        }
        entries[symbol] = entry
        if call[1] == "StateGraph" and not graph:
            graphs[symbol] = entry
    return [{**entry, "call": ".".join(entry["call"])} for entry in entries.values()]


def candidate_role(path):
    """Directory conventions are reviewable hints, never exclusion or edit permission."""
    parts = {part.casefold() for part in Path(path).parts[:-1]}
    if parts & {"synthetic_data", "scripts", "development", "devtools"}:
        return "development_utility"
    if parts & {"evals", "evaluations", "evaluation", "benchmarks", "scorers"}:
        return "evaluation"
    if parts & {"workers", "background", "jobs"}:
        return "background"
    return "unknown"


def dependency_proposals(tree, path, root):
    """Resolve local import paths without loading modules or widening the edit scope."""
    proposals = {}
    for node in ast.walk(tree):
        modules = []
        if isinstance(node, ast.Import):
            modules = [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom):
            base = node.module or ""
            if node.level:
                parent = Path(path).parent
                for _ in range(node.level - 1):
                    parent = parent.parent
                base = ".".join([*parent.parts, *base.split(".")]).strip(".")
            modules = [base, *(f"{base}.{alias.name}" for alias in node.names)]
        for module in modules:
            if not module or "*" in module:
                continue
            relative = Path(*module.split("."))
            for base in (root, root / "src"):
                candidates = [base / relative.with_suffix(".py"), base / relative / "__init__.py"]
                for target in candidates:
                    if target == root / path or not target.is_file():
                        continue
                    local_path = target.relative_to(root).as_posix()
                    if not eligible_suggestion(root, local_path):
                        continue
                    proposals.setdefault(
                        local_path,
                        {
                            "path": local_path,
                            "relationship": "imports",
                            "source_line": node.lineno,
                            "approved_for_edits": False,
                        },
                    )
                    break
    return sorted(proposals.values(), key=lambda item: item["path"])


def scan(root):
    root = Path(root).resolve()
    candidates = []
    coverage = {
        "inspected_files": 0,
        "scanned_files": 0,
        "scanned_bytes": 0,
        "excluded_files": 0,
        "unreadable_files": 0,
        "policy_excluded_files": 0,
        "excluded_directories": 0,
        "generated_files": 0,
        "oversized_files": 0,
        "parse_error_files": 0,
        "unsupported_patterns": 0,
        "omissions": [],
        "omitted_details": 0,
    }
    limits = []

    def omission(path, reason, action, **details):
        if len(coverage["omissions"]) < MAX_COVERAGE_DETAILS:
            coverage["omissions"].append(
                {"path": str(path), "reason": reason, "action": action, **details}
            )
        else:
            coverage["omitted_details"] += 1

    def finish():
        descriptions = [
            ("oversized_files", "source files exceed the size limit"),
            ("parse_error_files", "source files could not be parsed"),
            ("unreadable_files", "source files could not be read"),
            ("unsupported_patterns", "agent constructions need an explicit identity review"),
        ]
        messages = [
            f"{coverage[key]} {label}; review the named discovery omissions."
            for key, label in descriptions
            if coverage[key]
        ]
        return candidates, coverage, [*messages, *limits]

    local_modules = {
        name.split(".")[0]
        for name in PYTHON_ENTRYPOINTS
        if any(
            (base / (name.split(".")[0] + ".py")).exists()
            or (base / name.split(".")[0] / "__init__.py").exists()
            for base in (root, root / "src")
        )
    }
    for directory, dirs, files in os.walk(root, followlinks=False):
        retained_dirs = []
        for name in sorted(dirs):
            relative = (Path(directory) / name).relative_to(root)
            if not application_path(relative) or (Path(directory) / name).is_symlink():
                coverage["excluded_directories"] += 1
                continue
            retained_dirs.append(name)
        dirs[:] = retained_dirs
        for filename in sorted(files):
            file = Path(directory) / filename
            relative = file.relative_to(root)
            if file.suffix not in {".py", ".js", ".ts", ".tsx", ".jsx", ".mjs", ".cjs"}:
                continue
            if file.is_symlink() or not application_path(relative):
                coverage["excluded_files"] += 1
                coverage["policy_excluded_files"] += 1
                continue
            if coverage["inspected_files"] >= MAX_FILES or len(candidates) >= MAX_CANDIDATES:
                omission(
                    relative,
                    "scan_limit",
                    "Narrow the source selection or add an explicit binding.",
                )
                limits.append("Discovery scan limit reached; review the last scanned path.")
                return finish()
            try:
                coverage["inspected_files"] += 1
                size = file.stat().st_size
                if size > MAX_FILE_BYTES:
                    coverage["excluded_files"] += 1
                    coverage["oversized_files"] += 1
                    omission(
                        relative,
                        "file_size_limit",
                        "Review this file and add an explicit agent binding.",
                        bytes=size,
                        limit_bytes=MAX_FILE_BYTES,
                    )
                    continue
                if coverage["scanned_bytes"] + size > MAX_SCAN_BYTES:
                    omission(
                        relative,
                        "byte_limit",
                        "Narrow the source selection or add explicit bindings.",
                    )
                    limits.append("Source byte limit reached; review the last scanned path.")
                    return finish()
                with file.open("rb") as stream:
                    raw = stream.read(MAX_FILE_BYTES + 1)
                if len(raw) > MAX_FILE_BYTES:
                    coverage["excluded_files"] += 1
                    coverage["oversized_files"] += 1
                    omission(
                        relative,
                        "file_size_limit",
                        "Review this file and add an explicit agent binding.",
                        limit_bytes=MAX_FILE_BYTES,
                    )
                    continue
                if coverage["scanned_bytes"] + len(raw) > MAX_SCAN_BYTES:
                    omission(
                        relative,
                        "byte_limit",
                        "Narrow the source selection or add explicit bindings.",
                    )
                    limits.append("Source byte limit reached; review the last scanned path.")
                    return finish()
                source = raw.decode(errors="replace")
                coverage["scanned_files"] += 1
                coverage["scanned_bytes"] += len(raw)
                if generated(source):
                    coverage["excluded_files"] += 1
                    coverage["generated_files"] += 1
                    continue
                dependencies = []
                if file.suffix == ".py":
                    tree = ast.parse(source)
                    visitor = PythonEntries()
                    visitor.visit(tree)
                    entries = [
                        entry
                        for entry in visitor.entries.values()
                        if entry["call"].split(".")[0] not in local_modules
                    ]
                    for unresolved in visitor.unresolved:
                        if unresolved["constructor"].split(".")[0] in local_modules:
                            continue
                        coverage["unsupported_patterns"] += 1
                        omission(relative, **unresolved)
                    if entries:
                        dependencies = dependency_proposals(tree, relative, root)
                else:
                    entries = javascript_entries(source)
                candidates.extend(
                    {
                        **entry,
                        "path": relative.as_posix(),
                        "role": candidate_role(relative),
                        "role_source": "path_convention",
                        "dependency_proposals": dependencies[:30],
                        "dependency_proposals_omitted": max(0, len(dependencies) - 30),
                    }
                    for entry in entries[: MAX_CANDIDATES - len(candidates)]
                )
                if len(candidates) >= MAX_CANDIDATES:
                    limits.append("Agent suggestion limit reached; add remaining agents manually.")
                    return finish()
            except OSError:
                coverage["unreadable_files"] += 1
                omission(relative, "unreadable", "Check that this source file is readable.")
            except (SyntaxError, ValueError, RecursionError) as exc:
                coverage["parse_error_files"] += 1
                omission(
                    relative,
                    "parse_error",
                    "Review syntax or add an explicit agent binding without running this file.",
                    **({"line": exc.lineno} if isinstance(exc, SyntaxError) else {}),
                )
    return finish()
